### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by vaanwd** [rg-software/wlx-edge-viewer#1]
The following error appears when I try to install in Total Commander:

![screenshot](https://user-images.githubusercontent.com/70415/195772042-dd7c3cae-4589-4ad4-b329-20dc2dd4801f.png)

**Comment by rg-software** [comment]
What's your operating system and is it 32 or 64 bit? Please make sure to use the right plugin version (32/64).

**Comment by vaanwd** [comment]
> What's your operating system and is it 32 or 64 bit? Please make sure to use the right plugin version (32/64).

64 bits. Windows 10 21H2 19044.2130

**Comment by yahuudang** [comment]
64位win10系统，用的32位tc，装32位插件，也是报错。
手动安装后，预览提示如图
![20221024_042627](https://user-images.githubusercontent.com/4756893/197416580-d1298c1b-0a42-4f23-8b52-d83508b6eb3c.jpg)

**Comment by rg-software** [comment]
@yahuudang what is your specific Windows version (printed by `ver` command)?
Also try installing [WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).

**Comment by yahuudang** [comment]
Microsoft Windows [版本 10.0.19044.1766]
已经安装 WebView2 runtime 
安装EdgeViewer.wlx时报错如图片
![20221102_022803](https://user-images.githubusercontent.com/4756893/199310620-a92b8536-0098-40b3-bbd8-b5bd01897583.jpg)

**Comment by rg-software** [comment]
Try the newest update, I think I have fixed this error.
