### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by alabotski** [rg-software/wlx-edge-viewer#17]
When I try open any html or md
I have error

Version 1.0.7
![image](https://github.com/rg-software/wlx-edge-viewer/assets/439337/adeb294e-7774-4892-bdc1-ff002bcccaa8)

**Comment by alabotski** [comment]
Version 1.0.3

![image](https://github.com/rg-software/wlx-edge-viewer/assets/439337/b37efcc5-a808-473c-8951-21180beac11b)

**Comment by rg-software** [comment]
203 is "ERROR_ENVVAR_NOT_FOUND".
Please make sure that each env variable (%blabla%) in your `edgeviewer.ini` actually exists and its value is correct.

**Comment by alabotski** [comment]
I have default settings

```
[Extensions]
; should be uppercase to form the right detect string
HTML=SVG,HTM,HTML,XML,PDF
Markdown=MD,MARKDOWN
AsciiDoc=ADOC,ASCIIDOC
URL=URL
MHTML=MHT,MHTML

; also show directory contents
Dirs=1
DirImageExt=jpg|jpeg|png|gif|svg|bmp

[Chromium] 
; space-separated; check switches at:
; https://peter.sh/experiments/chromium-command-line-switches/
; (try, e.g, --disable-smooth-scrolling)
Switches=

; remove UserDir setting to use the plugin directory
UserDir=%USERPROFILE%

; uncomment to point to your fixed version Edge 
; BrowserExecutableX86Folder=%USERPROFILE%\Edge32
; BrowserExecutableX64Folder=%USERPROFILE%\Edge64

; remove EBWebView cache on exit
CleanupOnExit=0

; do not allow accessing external resources
OfflineMode=0

[Markdown]
; from the "markdown" subfolder
CSS=github.css

[AsciiDoc]
; from the "asciidoctor" subfolder
CSS=asciidoctor.css

```

**Comment by alabotski** [comment]
I reinstall edge also
But it doesn't help me

**Comment by rg-software** [comment]
No good ideas at the moment, this is the first time I get this kind of report. I'll add some diagnostic information, and we'll check again. For the time being, pls try replacing `UserDir=%USERPROFILE%` with `UserDir=C:\temp` or something like that (and make sure this folder exists).

**Comment by alabotski** [comment]
```
[ListerPlugins]
0=%COMMANDER_PATH%\plugins\wlx\Imagine\Imagine.wlx64
0_detect="MULTIMEDIA & (EXT="BMP" | EXT="JPG" | EXT="JPE" | EXT="JPEG" | EXT="JP2" | EXT="J2K" | EXT="PNG" | EXT="GIF" | EXT="TIF" | EXT="TIFF" | EXT="PSD" | EXT="TGA" | EXT="PCX" | EXT="PCD" | EXT="WMP" | EXT="WMF" | EXT="EMF" | EXT="AAI" | EXT="JXR" | EXT="WDP" | EXT="DICOM" | EXT="DCM" | EXT="WEBP" | EXT="PBM" | EXT="PPM" | EXT="HEIC" | EXT="DNG" | EXT="RAW" | EXT="CRW" | EXT="CR2" | EXT="NEF" | EXT="ORF" | EXT="ARW" | EXT="DCR" | EXT="MRW" | EXT="NRW" | EXT="PEF" | EXT="RAF" | EXT="SRF" | EXT="X3F" | EXT="MEF" | EXT="SRW" | EXT="3FR" | EXT="MDC" | EXT="RW2" | EXT="ERF" | EXT="MOS" | EXT="KDC" | EXT="SR2" | EXT="CR3")"
1=%COMMANDER_PATH%\plugins\wlx\EdgeViewer\EdgeViewer.wlx64
1_detect="EXT="HTM" | EXT="HTML" | EXT="MHT" | EXT="MHTML" | EXT="XML" | EXT="MD" | EXT="MARKDOWN" | EXT="ADOC" | EXT="ASCIIDOC""
2=%COMMANDER_PATH%\plugins\wlx\TCSumatraPDF\SumatraPDF.wlx64
2_detect="MULTIMEDIA & (EXT="PDF" | EXT="DJVU" | EXT="DJV"| EXT="XPS" | EXT="CBZ" | EXT="CBR" | EXT="EPUB" | EXT="MOBI" | EXT="CHM" | EXT="AI" | EXT="CB7" | EXT="CBT" | EXT="KF8" | EXT="AZW" | EXT="AZW3" | EXT="PRC" | EXT="TCR" | EXT="PDB" | EXT="FB2" | EXT="FB2Z" | EXT="ZFB2" | EXT="FBZ" | EXT="JP2" | EXT="WEBP")"
3=%COMMANDER_PATH%\Plugins\wlx\TCTorrent\TCTorrent.wlx64
3_detect="EXT="TORRENT""
4=%COMMANDER_PATH%\plugins\wlx\AKFont\AKFont.wlx64
4_detect="FORCE | EXT="TTF" | EXT="PFM" | EXT="OTF" | EXT="TTC" | EXT="FON" | EXT="PFB""
5=%COMMANDER_PATH%\plugins\wlx\fileinfo\fileinfo.wlx64
6=%COMMANDER_PATH%\Plugins\wlx\CudaLister\cudalister.wlx64
```

If I open MD (html) for viewing. The plugin is skipped by EdgeViewer and processed by cudalist
It’s just strange that before all this worked without problems

**Comment by rg-software** [comment]
I have a [quick update](https://www.dropbox.com/scl/fi/yy22k86ipqa3i96r8fdzm/Release-20231119.zip?rlkey=19f8g03jva0fockyuak9ty9nb&dl=0) that should display error messages properly. However, I guess it won't solve your issue, but try it just in case.

Nobody else reported this error. I checked the code, it should handle most abnormal situations properly, so the error message should be reliable. Try the plugin on a freshly depacked TC. Make sure TC is installed into a writeable, plain ascii-path directory and comment out the `UserDir=` line.

**Comment by alabotski** [comment]
@rg-software 

Hi

![image](https://github.com/rg-software/wlx-edge-viewer/assets/439337/7d236d92-864b-43e4-8456-4ef8cf759c19)

One thing I delete edge
But I use another browser
May be problem in it?

**Comment by rg-software** [comment]
Yes, it needs Edge. If you want to use this plugin but don't want to have Edge in your system, you can download the [Fixed Version](https://developer.microsoft.com/en-us/microsoft-edge/webview2#download-section), depack it somewhere and use `BrowserExecutableX64Folder` path in the plugin ini file.
