### ISSUE TITLE
crashes with "Cannot create WebView2. Error Code: 203"

### ISSUE THREAD

**Issue by adoeller** [rg-software/wlx-edge-viewer#2]
and closes TC as well

**Comment by rg-software** [comment]
What is your operaring system version and is it 32 or 64 bit? In any case, try installing Webview2 runtime.

**Comment by adoeller** [comment]
its 64bit.

You are right, the Webview2 runtime is missing on one of my computers. But I feel, the addon should not crash the whole TC because of a missing library. I was not aware that an additional runtime was needed. Its not mentioned.

**Comment by rg-software** [comment]
Well, it is mentioned for Win 7 & 8, but for Win 10 WebView2 is a part of the regular update routine, so I don't really know which revision included it. In any case, I agree I need to add some graceful exit capability -- will do it when I find a device to test this behavior.

**Comment by adoeller** [comment]
This is a company Win 20 installation that lacks the WebView2 part ...
