### ISSUE TITLE
German Umlaute (äöü etc.) are not correctly displayed in Markdown preview

### ISSUE THREAD

**Issue by kernal64** [rg-software/wlx-edge-viewer#25]
What steps will reproduce the issue?

1.create a readme.md
2.activate the preview

What is the expected result?

-> all UTF-8-chars should be displayed correctly

What happens instead?

-> there are only '?' shown for Umlauts

**Comment by rg-software** [comment]
Try this example, it works for me.
[test.md](https://github.com/rg-software/wlx-edge-viewer/files/14054053/test.md)

**Comment by kernal64** [comment]
The Scite (Editor) converted my MD from UTF-8 to some ANSI-codepage. I converted the text back to UTF-8 and it works. Sorry for this.

**Comment by rg-software** [comment]
You're welcome.

BTW, I am not sure how markdown is supposed to be handled in case of non-utf8, so perhaps no real support for ANSI here.
