### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by zrrui** [rg-software/wlx-edge-viewer#3]
My operating system is 64 bit,But I usually use 32 bit TC,and only 64-bit plugins can work,Can you make a 32-bit and 64-bit mixed plugin?Can it support txt viewing?
  It can't call other plugins using "4" shortcut keys

**Comment by rg-software** [comment]
Yes, I am planning to make it mixed. Unfortunately, WebView2 comes with two different DLL libraries having the same name, so I can't ship them both in the same package. So it is planned, but not sure how quickly I can make it.

I can add txt support, but what's the point? Isn't built-in lister good enough?

Will think about `4`. I check my installed plugins and it seems that most of them don't support `4` either :)

**Comment by vaanwd** [comment]
> Yes, I am planning to make it mixed. Unfortunately, WebView2 comes with two different DLL libraries having the same name, so I can't ship them both in the same package. So it is planned, but not sure how quickly I can make it.
> 
> I can add txt support, but what's the point? Isn't built-in lister good enough?
> 
> Will think about `4`. I check my installed plugins and it seems that most of them don't support `4` either :)

You can put them in separate directories: x86, x64 for example

**Comment by zrrui** [comment]
It is useful to support viewing txt,The built-in lister can't change font size quickly, and, I like to use Edge to read txt text aloud

**Comment by zrrui** [comment]
I found that edgeviewer will create an EBWebView folder and edgeviewer.ini in the TC path, instead of in its own folder,it seems to be a problem.
certainly,this can be done by modifying wincmd.ini and adding EdgeViewer.wlx=%COMMANDER_PATH%\Plugins\WLX\EdgeViewer\edgeviewer.ini in the [ReplaceIniLocation] section

**Comment by rg-software** [comment]
> It is useful to support viewing txt,

OK, got it.

> I found that edgeviewer will create an EBWebView folder and edgeviewer.ini in the TC path, instead of in its own folder,it seems to be a problem.

Well, this is by design, because this approach is explicitly suggested in the plugin dev guide:

> _This is a fully qualified path+file name, and will be in the same directory as the wincmd.ini. It's recommended to store the plugin data in this file or at least in this directory, because the plugin directory or the Windows directory may not be writable!_

**Comment by rg-software** [comment]
> You can put them in separate directories: x86, x64 for example

I managed to get rid of `WebView2Loader.dll`, which caused this trouble; so the next release is going to be unviersal.

**Comment by rg-software** [comment]
Try the newest update, it has resovled some of the issues mentioned here.
